name: "Tag on Pull Request merge"

on:
  pull_request:
    types: 
      - closed
    branches:
      - main
jobs:
  tag-on-pr-merge:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Tag on PR merge
        id: tag-on-pr-merge
        uses: David-Lor/action-tag-on-pr-merge@main
        with:
          tag-regex: true
          push-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: print tag
        run:  echo "${{ steps.tag-on-pr-merge.outputs.tag }}"
